### ISSUE TITLE
Expected sql object and actual object assesrtion doesn't hold true

### ISSUE THREAD

**Issue by ahmedhr** [rajivsarvepalli/mock-alchemy#151]
**Describe the bug**
Like the example given in the documentation
```
    expected_anyalsis3 = CombinedAnalysis(3, some, anyalsis, values)
    anyalsis3 = session.query(CombinedAnalysis).get({"pk1": 3})
    assert anyalsis3 == expected_anyalsis3
```
The above assertion fails, however the column values are same but the `_sa_instance` is different for both the objects. 

**Expected behavior**
The assertion should not consider the instance id

Possible solutions
1. Assertion method to check only values

- OS: debian
- Version : SQLAlchemy==1.4.23

**Comment by rajivsarvepalli** [comment]
Not sure I fully understand, can you give more context into what exactly you ran?

The example in the documentation is merely exemplary to what this library can perform, and not directly runnable.

If the assertion is failing due to unequal objects, then you can implement an `__eq__`  on the object to do the comparison the way you desire. The assertion behavior is not determined by this library, but by python itself (the same as the `==` operator). The default `__eq__` for an SQLAlchemy object inheriting from Base may not always serve your needs.

Again, I could be misunderstanding what you are saying, so feel free to comment explaining what I missed.

**Comment by rajivsarvepalli** [comment]
Closing issue. Feel free to re-open if you feel there is more to this issue that I am missing.

**Comment by ahmedhr** [comment]
> Not sure I fully understand, can you give more context into what exactly you ran?
> 
> The example in the documentation is merely exemplary to what this library can perform, and is not directly runnable.
> 
> If the assertion is failing due to unequal objects, then you can implement an `__eq__` on the object to do the comparison the way you desire. The assertion behavior is not determined by this library, but by python itself (the same as the `==` operator). The default `__eq__` for an SQLAlchemy object inheriting from Base may not always serve your needs.
> 
> Again, I could be misunderstanding what you are saying, so feel free to comment explaining what I missed.

@rajivsarvepalli Yes you are right, I figured this while digging into the assertion, thanks!
